tplProjectName: mobilebuilder_tpl_7_9_0
â†“FCMPushNotifications [mobile.components.UIActionStack-1591517891678]: ğŸ— mobileSharedActions/FCMPushNotifications.yaml
â†“DemoPage [mobile.components.PageComponent-1591517856447]: ğŸ— mobilePages/DemoPage.yaml